### PR TITLE
ci: Run workflow on pull requests as well

### PR DESCRIPTION
**Pull request by perlpunk**

### CODE REVIEW

**Review by mimi1vx — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Comment by grisu48** [comment]
Hello @perlpunk, can you please rebase? I think the CI failures are related to the workflow still using go 1.20 (no generics), fixed by @mimi1vx in https://github.com/os-autoinst/openqa-mon/pull/166

**Comment by Martchus** [comment]
@Mergifyio rebase

**Review by grisu48 — APPROVED** [review]
Thank you!

**Comment by grisu48** [comment]
@perlpunk would it be possible to sign the commit?

**Pull request merged**
